In [6]:
# Implementation OR Problem

import torch
from torch.autograd import Variable

In [7]:
x_arr = Variable(torch.Tensor([[0,0],[0,1],[1,0],[1,1]]),requires_grad=True)
x_arr

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]], requires_grad=True)

In [8]:
y_arr = Variable(torch.Tensor([[0],[1],[1],[1]]),requires_grad=True)
y_arr

tensor([[0.],
        [1.],
        [1.],
        [1.]], requires_grad=True)

In [9]:
class network():
    def __init__(self):
        self.w1=0
        self.w2=0 
        self.b=0
        self.lr=0.01

    def y_calc(self,X_arr,Y_arr):
        self.sum=0
        self.Y_arr = Y_arr
        self.X_arr = X_arr
        for i in range(0,len(self.X_arr)):
            self.itr = i
            self.sum = self.sum + (self.w1*self.X_arr[i][0]) + (self.w2*self.X_arr[i][1])
            self.y_in = self.sum + self.b
            self.activation()

    def activation(self):
        if(self.y_in > 0):
            self.y = 1
        else:
            self.y = 0
        self.match()

    def match(self):
        if(self.y!=self.Y_arr[self.itr]):
            self.w1 = self.w1 + self.lr*(self.Y_arr[self.itr]-self.y)*self.X_arr[self.itr][0]
            self.w2 = self.w2 + self.lr*(self.Y_arr[self.itr]-self.y)*self.X_arr[self.itr][1]
            self.b = self.b + self.lr*(self.Y_arr[self.itr]-self.y)
            self.display()

    def display(self):
        print(self.w1)
        print(self.w2)

    


In [10]:
net = network()
net.y_calc(x_arr,y_arr)

tensor([0.], grad_fn=<AddBackward0>)
tensor([0.0100], grad_fn=<AddBackward0>)
